apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-appjs
spec:
  replicas: 3

  selector:
    app: web

  template:
    metadata:
      labels:
        app: web
        name: appjs
    spec:
      containers:
      - image: smlinux/appjs
        name: appjs-container
        ports:
        - containerPort: 8090
